tables:
  - name: accounts
    source_table: negarabank.bronze.accounts
    target_table: negarabank.silver.accounts
    business_key: account_id
    scd2:
      tracked_columns:
        - account_type
        - balance
        - status
      effective_date_column: load_date
    transform_sql: |
      SELECT
        CAST(account_id   AS BIGINT)         AS account_id,
        CAST(customer_id  AS BIGINT)         AS customer_id,
        UPPER(TRIM(account_type))            AS account_type,
        CAST(balance      AS DECIMAL(15, 2)) AS balance,
        UPPER(TRIM(status))                  AS status,
        CAST(open_date    AS TIMESTAMP)      AS open_date,
        CAST(credit_limit AS DECIMAL(15, 2)) AS credit_limit,
        load_date,
        load_timestamp
      FROM negarabank.bronze.accounts
      QUALIFY ROW_NUMBER() OVER (PARTITION BY account_id ORDER BY load_timestamp DESC) = 1
    dq:
      not_null: [account_id, customer_id]
      unique: [account_id]

  - name: customers
    source_table: negarabank.bronze.customers
    target_table: negarabank.silver.customers
    business_key: customer_id
    scd2:
      tracked_columns:
        - phone
        - email
        - city
        - province
        - kyc_status
        - risk_score
        - segment
      effective_date_column: load_date
    transform_sql: |
      SELECT
      customer_id,full_name,nik,phone,email,city,province,registration_date,kyc_status,risk_score,segment
        CAST(customer_id  AS BIGINT)         AS customer_id,
        CAST(full_name    AS STRING)         AS full_name,
        CAST(nik          AS STRING)         AS nik,
        CAST(phone        AS STRING)         AS phone,
        CAST(email        AS STRING)         AS email,
        CAST(city         AS STRING)         AS city,
        CAST(province     AS STRING)         AS province,
        CAST(registration_date AS TIMESTAMP) AS registration_date,
        CAST(kyc_status   AS STRING)         AS kyc_status,
        CAST(risk_score   AS DECIMAL(15, 2))  AS risk_score,
        CAST(segment      AS STRING)         AS segment,
        load_date,
        load_timestamp
      FROM negarabank.bronze.customers
      QUALIFY ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY load_timestamp DESC) = 1
    dq:
      not_null: [customer_id]
      unique: [customer_id]

  - name: transactions
    source_table: negarabank.bronze.transactions
    target_table: negarabank.silver.transactions
    business_key: transaction_id
    scd2:
      tracked_columns:
        - status
      effective_date_column: load_date
    transform_sql: |
      SELECT
        CAST(t.transaction_id AS BIGINT)         AS transaction_id,
        CAST(t.account_id     AS BIGINT)         AS account_id,
        CAST(t.customer_id    AS BIGINT)         AS customer_id,
        CAST(t.amount         AS DECIMAL(15, 2)) AS amount,
        CAST(t.txn_date       AS TIMESTAMP)      AS txn_date,
        UPPER(TRIM(t.status))                    AS status,
        UPPER(TRIM(t.channel))                   AS channel,
        CASE WHEN a.account_id IS NOT NULL THEN 'true' ELSE 'false' END AS reconciled,
        t.load_date,
        t.load_timestamp
      FROM negarabank.bronze.transactions t
      LEFT JOIN negarabank.silver.accounts a
        ON t.account_id = a.account_id AND a.is_current = true
      QUALIFY ROW_NUMBER() OVER (PARTITION BY t.transaction_id ORDER BY t.load_timestamp DESC) = 1
    dq:
      not_null: [transaction_id, account_id]
      unique: [transaction_id]
